name: 1-minute-cronjob-update-view
on:
  schedule:
    - cron: "*/1 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call update-view api
        run: |
          curl --request POST \
          --url 'https://${{ secrets.API_URL }}/api/cronjob/update-view' \
          --header 'authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
